# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: lupnt-env
channels:
  - pytorch-nightly
  - conda-forge
  - gurobi
  - defaults
dependencies: 
  - numpy
  - astropy
  - cvxpy
  - dataset
  - filterpy
  - matplotlib
  - mlflow
  - mlflow-skinny
  - networkx
  - numba
  - onnx
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - Pillow
  - plotly
  - scikit-learn
  - scipy
  - setuptools
  - spiceypy
  - tqdm
  - mypy
  - ipywidgets
  - ipympl
